#Configuration ref: https://docs.docker.com/compose/compose-file/#reference-and-guidelines
#No need to create network. Docker v2 and above creates marketsurveyapp_default on run.
version: "2"
services:     
  api:
    build: 
      context: .
      dockerfile: api/Dockerfile_compose
    image: webapp-api #New image. Settings defined in Dockerfile in /api
    restart: always
    ports:
      - "5000:5000" #As defined in Dockerfile
    volumes: #specifies directory to be shared with another service as a volume
      - ./api:/api 
      - /api/node_modules
    networks: 
      app:
        aliases:
          - api
  client:
    build: 
      context: .
      dockerfile: client/Dockerfile_compose
    image: webapp-client  #New image. Settings defined in Dockerfile in /client
    restart: always
    ports:
      - "3000:3000" #As defined in Dockerfile
    volumes: #specifies directory to be shared with another service as a volume
      - ./client:/client 
      - /client/node_modules
    networks: 
      app:
        aliases:
          - client
    links:
      - api
    stdin_open: true #MUST to prevent React containers from crashing after "npm build". Ref: https://github.com/facebook/create-react-app/issues/8688
networks: 
  app: