#Configuration ref: https://docs.docker.com/compose/compose-file/#reference-and-guidelines
#No need to create network. Docker v2 and above creates marketsurveyapp_default on run.
version: "2"
services:     
    api:
        build: #Specifies Dockerfile to use to build image
            context: ./api
            dockerfile: Dockerfile
        image: webapp-api:api
        container_name: api
        restart: on-failure
        ports:
            - "5000:5000" #Host port on the left, container port on the right. Network uses container port. Ref: https://docs.docker.com/compose/networking/
        volumes: #specifies directory to be shared with another service as a volume
            - ./api:/api 
            - /api/node_modules
    client:
        build: #Specifies Dockerfile to use to build image
            context: ./client
            dockerfile: Dockerfile
        image: webapp-client:client #Needed for docker-compose to find this container under "docker run --network container:container_name \"
        restart: on-failure
        ports:
            - "3000:3000" #Host port on the left, container port on the right. 
        volumes: #specifies directory to be shared with another service as a volume
            - ./client:/client 
            - /client/node_modules